### ISSUE TITLE
Viewing both unit and instrumentation test coverage

### ISSUE THREAD

**Issue by riwnodennyk** [codecov/example-android#5]
Really nice job with codecov! But is there currently a way to see unit and instrumentation test coverages separately in Codecov? Would be really useful.

**Comment by stevepeak** [comment]
Hey @riwnodennyk currently there is and even more so in our next release.

In both cases you will need to submit the coverage in separately. Here is an example:

```
# current release
bash <(curl -s https://codecov.io/bash) -b unittests -f unittests.coverage.xml
bash <(curl -s https://codecov.io/bash) -b instrumentation -f instrumentation.coverage.xml
```
> The `-b` is replacing the build argument

```
# future (next release)
bash <(curl -s https://codecov.io/bash) -F unittests -f unittests.coverage.xml
bash <(curl -s https://codecov.io/bash) -F instrumentation -f instrumentation.coverage.xml
``
> The `-F` is used as a "flag".
