### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by PanosSakkos** [codecov/example-android#7]
Hi,

I followed your gradle and travis settings but there is no [report uploaded](https://travis-ci.org/dono-app/android/builds/138444652).

Also I can't see any [coverage results](https://codecov.io/gh/codecov/example-android) for your example, so I believe that means that it's indeed wrong.

:panos

**Comment by arturdm** [comment]
Hi @PanosSakkos,

please look into your Travis builds logs for errors and executed Gradle tasks. For instance https://travis-ci.org/dono-app/android/builds/139000975 shows that it does not run `jacocoTestReport` task at all. Try moving those tasks from `after_success` to `script` block instead (your script also does unnecessary `cd src` and it may cause `script` phase to fail).
