### ISSUE TITLE
No compatible devices connected.[TestRunner] FAILED

### ISSUE THREAD

**Issue by alessandrojp** [codecov/example-android#8]
Hi,

I saw that you had the same problem that I have now.
Do you remember what you did to fix that?
https://travis-ci.org/codecov/example-android/builds/94016684

```
FREE > : No compatible devices connected.[TestRunner] FAILED 
Found 1 connected device(s), 0 of which were compatible.
:sample-app:connectedFreeDebugAndroidTest FAILED
```

**Comment by stevepeak** [comment]
@arturdm thoughts? I don't recall this issue before

**Comment by arturdm** [comment]
@alessandrojp - what are your app's `minSdkVersion` and `targetSdkVersion` and what version of the emulator are you starting on travis?

You may try to look at this example's [build.gradle](https://github.com/codecov/example-android/blob/master/sample-app/build.gradle) and [.travis.yml ](https://github.com/codecov/example-android/blob/master/.travis.yml) files. There's `minSdkVersion` set to API 15 and the emulator version started on Travis is also set to 15.
